### ISSUE TITLE
Does not support rotated/flipped display

### ISSUE THREAD

**Issue by djsburra** [MindShow/USBDisplay#109]
- I want to use this converter for a screen I have rotated 90degrees (portrait flipped), but the display either goes blank or distorts/doubles.

**Comment by Coffee606** [comment]
Any update on this? :)

**Comment by muzaffarmhm** [comment]
Hi, Try the latest version which can be downloaded from the #[website](http://www.ultrasemi.com/usbdisplay/index.html). This one supports the portrait mode

**Comment by daniel-bmec-co** [comment]
@muzaffarmhm 

That website gives a 404 error. Anyway, I'd rather get the latest release from here on github.

**Comment by djsburra** [comment]
@muzaffarmhm, 
>...the #[website](http://www.ultrasemi.com/usbdisplay/index.html)...

This worked for me, thanks for the help!

**Comment by djsburra** [comment]
[latest drivers](http://www.ultrasemi.com/usbdisplay/index.html). are here.
