### ISSUE TITLE
Windows 11 Extend screen Problem

### ISSUE THREAD

**Issue by viniciusbenicio** [MindShow/USBDisplay#14]
It doesn't work on Windows 11 to extend screen with another onboard hdmi but when I use only the adapter it works normal.

Screen keeps going back and forth all the time

I did the administrator mode installation

**Comment by MindShow** [comment]
extend or duplicate ?

**Comment by viniciusbenicio** [comment]
> extend or duplicate ? we will fix duplicate fail problem with dual GPU

Extend. 

Thanks. My laptop have gtx 1650

**Comment by viniciusbenicio** [comment]
When new update ?

Thanks

**Comment by carsimoes** [comment]
same problem here on W11

**Comment by viniciusbenicio** [comment]
@MindShow  do you have news?

**Comment by MindShow** [comment]
next verison will sovle this in a month

**Comment by viniciusbenicio** [comment]
@MindShow Thanks

**Comment by aparico** [comment]
@MindShow I have the same problem. My OS is Windows 10 and my GPU is capable of multiple display (GeForce GTX 1060)

**Comment by viniciusbenicio** [comment]
@MindShow do you have news for new update driver ?

**Comment by viniciusbenicio** [comment]
@MindShow do you have news?

**Comment by MindShow** [comment]
updated

**Comment by viniciusbenicio** [comment]
not resolve my problem and problem in extend for two monitor in my notebook with dual GPU.

And I use 1 monitor in HDMI and another monitor in adapter

obs.: The screen flickers when you leave the setting on extend

![image](https://user-images.githubusercontent.com/63131764/149167737-c9d59d4c-691b-4a92-9b99-b772aac8cece.png)


Help me

**Comment by viniciusbenicio** [comment]
@MindShow Can you check please?

[WinUsbDisplay.log](https://github.com/MindShow/USBDisplay/files/7856000/WinUsbDisplay.log)
