### ISSUE TITLE
Hello, please add support to Windows ARM version

### ISSUE THREAD

**Issue by kmille36** [MindShow/USBDisplay#19]
I'm using tablet with windows arm version so that driver for 64bit system won't work on arm64. Please add support to it. Thanks

**Comment by MindShow** [comment]
thanks for your advice

**Comment by kmille36** [comment]
By the way, my device come with Snapdragon 845 with Adreno 630 GPU. I tried install lastest version but it make my device reboot in finish installation step (not working).

**Comment by kmille36** [comment]
Here is log file:
[WinUsbDisplay.log](https://github.com/MindShow/USBDisplay/files/8177493/WinUsbDisplay.log)

**Comment by MindShow** [comment]
x86 / 64  only,not support arm

**Comment by kmille36** [comment]
Can it possible in future?

**Comment by kmille36** [comment]
I tested on Android it work fine (ARM). Can you porting it into windows? Thanks.

**Comment by MindShow** [comment]
this version support arm http://www.ultrasemi.com/usbdisplay/Windows/USMDisplay_Windows.exe
