### ISSUE TITLE
Portrait mode doesn't work on WIndows 10 Pro

### ISSUE THREAD

**Issue by lucas-santanna** [MindShow/USBDisplay#2]
Hello! For devices with windows 10 pro, when choosing the view for portrait mode  (vertical monitor), the driver doesn't work

**Comment by MindShow** [comment]
thanks for your information， i will check that

**Comment by MindShow** [comment]
can not support

**Comment by juan9900** [comment]
> can not support

Do you mean it can't be implemented in the future?
