### ISSUE TITLE
Ubuntu 20 support !!!! :(

### ISSUE THREAD

**Issue by med-amine-ghanmi** [MindShow/USBDisplay#20]
any solution for ubuntu users ?? :(

**Comment by raheelhirani35** [comment]
Hi Please update this driver for ubuntu 20.. Need it desperately please!!

**Comment by tiagofga** [comment]
Any update for Ubuntu?

**Comment by MindShow** [comment]
send email to  ```csliu@ultrasemi.com```  get the test version driver for linux

**Comment by MindShow** [comment]
#21

**Comment by OmegaGamage** [comment]
@MindShow

**Comment by santimakci** [comment]
Hi! Are there drivers for ubuntu 22.04? I would appreciate if someone could send me

**Comment by bemfica** [comment]
https://github.com/MindShow/USBDisplay/issues/21#issuecomment-1457952439 files and tips provided here
