### ISSUE TITLE
App restarts continuously in windows

### ISSUE THREAD

**Issue by chepo92** [MindShow/USBDisplay#24]
App restarts continuously in windows 10, version 21H2
Notebook: Toshiba Qosmio x75-A

```
[  904/ 1620] 2022-04-18 23:35:49:818 ! #################################################################################
[  904/ 1620] 2022-04-18 23:35:49:818 ! WinUsbDisplay Start
[  904/ 1620] 2022-04-18 23:35:49:861 ! ### System Info ---> MajorVer: 10, MinorVer: 0, BuildNumber: 19044 , Is64:1 
[  904/ 1620] 2022-04-18 23:35:49:861 ! ### CPU Info ---> wProcessorArchitecture: 0, dwProcessorType: 586, nums: 8
[  904/ 1620] 2022-04-18 23:35:49:876 ! ### GPU Info ---> Sum 6 Gpu Card
[  904/ 1620] 2022-04-18 23:35:49:876 ! ### GPU Info --- ---> display card: NVIDIA GeForce GTX 770M
[  904/ 1620] 2022-04-18 23:35:49:876 ! ### GPU Info --- ---> display card: Intel(R) HD Graphics 4600
[  904/ 1620] 2022-04-18 23:35:49:876 ! ### GPU Info --- ---> display card: Intel(R) HD Graphics 4600
[  904/ 1620] 2022-04-18 23:35:49:876 ! ### GPU Info --- ---> display card: Intel(R) HD Graphics 4600
[  904/ 1620] 2022-04-18 23:35:49:877 ! ### GPU Info --- ---> display card: Intel(R) HD Graphics 4600
[  904/ 1620] 2022-04-18 23:35:49:877 ! ### GPU Info --- ---> display card: Microsoft Basic Render Driver
[  904/ 9820] 2022-04-18 23:35:50:080 ! Win8ScreenDriverImpl Catched WinDxCriticalException: Can't DuplicateOutput(), (-2005270524)
[  904/ 9820] 2022-04-18 23:35:50:181 ! Win8ScreenDriverImpl has an invalid state. The invalid state can be a part of screen propery changes. An update signal will be generated as a screen size changed signal.
[  904/ 9820] 2022-04-18 23:35:50:181 ! ScreenDriverUpdate detected
[  904/ 8736] 2022-04-18 23:35:50:182 ! ScreenDriverUpdate detected
[  904/ 8736] 2022-04-18 23:35:50:182 ! Win8ScreenDriverImpl can't be successfully initialized
[  904/ 8736] 2022-04-18 23:35:50:182 ! errorcode str = -2005270524
[  904/ 8736] 2022-04-18 23:35:50:182 ! errorcode int = -2005270524
[  904/ 8736] 2022-04-18 23:35:52:183 ! ApplicationRestart::Restart() 0
[  904/ 8736] 2022-04-18 23:35:52:185 ! flag 0，Session 0，UsbDetector::systemStatus -1
[  904/ 8736] 2022-04-18 23:35:52:185 ! ApplicationRestart::Restart() 2
[  904/ 8736] 2022-04-18 23:35:52:190 ! ApplicationRestart::Restart() 3
﻿[ 9344/10972] 2022-04-18 23:35:52:2

78 ! #################################################################################
```

[WinUsbDisplay - copia.log](https://github.com/MindShow/USBDisplay/files/8509721/WinUsbDisplay.-.copia.log)

**Comment by chepo92** [comment]
I just read closed issues #4 #6 and #7 are the same, related to dual GPU
Proposed workaround 1: 
If you have dual monitors or dual graphics cards, please go to System>Display>Graphics and set the graphics option of MS USB Display to integrated graphics.
In my case I didn't found such config. 

Workaround 2: 
Go to system > device manager, then disable the dedicated GPU.

**Comment by MindShow** [comment]
方法一：
桌面--> 鼠标右键 --> 显示设置 -->图形设置 -->MS USB Display Setup -->选项 -->图形首选项 ，切花不同模式尝试

![image](https://user-images.githubusercontent.com/3387225/166880773-fa204baa-30a3-4745-afac-2dec49ebf328.png)

![image](https://user-images.githubusercontent.com/3387225/166880806-d39ee901-6139-48cf-ae97-c0712d2b6ec7.png)

![image](https://user-images.githubusercontent.com/3387225/166880730-5140ae9f-89a5-4238-b2d4-f4067a181458.png)

![image](https://user-images.githubusercontent.com/3387225/166880694-4938c180-9ece-42f6-bb16-bc505a114eb1.png)

方法二：
NVDIA 控制面板，管理3D设置，切换不同选项尝试
![98d29be1ee6c8236b7596b57ecdffc4](https://user-images.githubusercontent.com/3387225/166881069-8f2ddca6-ce9f-43ff-8775-2cc3ea6b3ba5.jpg)

**Comment by chepo92** [comment]
ok I found it, i had to examine and search for the app as it was not listed in the apps. 

![image](https://user-images.githubusercontent.com/26207806/167780532-657ea1c3-5667-49b5-a705-d26d78a26529.png)
