### ISSUE TITLE
Add support for portrait view

### ISSUE THREAD

**Issue by LD9797** [MindShow/USBDisplay#26]
Portrait view is not possible for win 10.

**Comment by MindShow** [comment]
not support

**Comment by filipe0li** [comment]
Is it possible to implement this feature?

**Comment by RandomArray** [comment]
Maybe if the actual code was here, the community could possibly implement this feature. GitHub's motto is “developers first”, yet this repo only contains installer archives without source code of any type.

**Comment by juan9900** [comment]
I hope portrait mode is implemented any time soon

**Comment by MindShow** [comment]
in planning，
linux first，
then macos extend
then portrait mode

**Comment by gwa100** [comment]
it has been a year, wheres the updates, also @LD9797 just return the adapter, the software is bad and makes it a scam basically
