### ISSUE TITLE
Device repeatedly disconnecting and reconnecting

### ISSUE THREAD

**Issue by markajleejr** [MindShow/USBDisplay#32]
I am on Windows 10 Pro and installed "MSDisplay_MultiDev_v1.0.0.18.0". The device will initially connect but, before anything can display, it will disconnect. After a few second, it'll reconnect again and repeat the process. I tried installing [FrescoDriver](https://support.frescologic.com/portal/en/kb/articles/usb-3-0-v) but it had no affect.

**Comment by dylan1114** [comment]
https://github.com/MindShow/USBDisplay/issues/7
You might be dealing with this issue.

Translated solution: 'If you have dual monitors or dual graphics cards, please go to System>Display>Graphics and set the graphics option of MS USB Display to integrated graphics.'

**Comment by markajleejr** [comment]
> Translated solution: 'If you have dual monitors or dual graphics cards, please go to System>Display>Graphics and set the graphics option of MS USB Display to integrated graphics.'

I may have made a wrong turn. I thought I followed the steps but ended up here with no option for 'Integrated graphics'
![image](https://user-images.githubusercontent.com/107655110/174494350-9bc1bdd5-d6e3-49d2-a121-399495e7e458.png)
Was I supposed to click on Graphic settings or is there something that specifically says graphics?
![image](https://user-images.githubusercontent.com/107655110/174494405-86ca7a67-92b6-4268-9cce-6ca216aac807.png)

**Comment by dylan1114** [comment]
> > Translated solution: 'If you have dual monitors or dual graphics cards, please go to System>Display>Graphics and set the graphics option of MS USB Display to integrated graphics.'
> 
> I may have made a wrong turn. I thought I followed the steps but ended up here with no option for 'Integrated graphics' ![image](https://user-images.githubusercontent.com/107655110/174494350-9bc1bdd5-d6e3-49d2-a121-399495e7e458.png) Was I supposed to click on Graphic settings or is there something that specifically says graphics? ![image](https://user-images.githubusercontent.com/107655110/174494405-86ca7a67-92b6-4268-9cce-6ca216aac807.png)

That's the right setting, try the Power Saving (Intel UHD) option. That should be the integrated graphics.

**Comment by MindShow** [comment]
have not found solution for  multi GPU

**Comment by MindShow** [comment]
try this http://www.ultrasemi.com/usbdisplay/Windows/USMDisplay_Windows.exe
and refer to #16
