### ISSUE TITLE
Trojan and Malicious file

### ISSUE THREAD

**Issue by bankh** [MindShow/USBDisplay#37]
An online scan for [MSDisplay_MultiDev_v1.0.0.18.0.exe] (https://github.com/MindShow/USBDisplay/blob/main/WinDows/MSDisplay_MultiDev_v1.0.0.18.0.exe) results in a detection of malicious and trojan content. To be more specific: Trojan.Zenpak.azu Trojan.Win32.Agent.oa!s1
Does anyone else have similar issue?

**Comment by asmodianx** [comment]
https://www.joesandbox.com/analysis/672930/0/html

**Comment by asmodianx** [comment]
The above link is to the new version of the driver. 
The version bankh listed however does not show as malicious: https://www.joesandbox.com/analysis/672989/0/html

**Comment by tomck** [comment]
> https://www.joesandbox.com/analysis/672930/0/html

This has since updated itself to say malicious.
