### ISSUE TITLE
Display ok, but no mouse and low FPS.

### ISSUE THREAD

**Issue by italocjs** [MindShow/USBDisplay#38]
Using the latest version driver, on windows 10. i cant see the mouse on the screen, and the fps is really low (~1 per second).  Any ideas on what could be the issue?  i had tried selecting winusb to only use the internal GPU.   If i try changing resolution on "view settings", both monitors are identified as 1.

Full log
[WinUsbDisplay.log](https://github.com/MindShow/USBDisplay/files/9185231/WinUsbDisplay.log)
:

**Comment by italocjs** [comment]
I traced it down to the second GPU, if i disable it, the software works just fine.   I tried following the instructions to force it to use the integrated GPU, both at nvidia settings and windows settings, but its not working.  Any idea on other way to fix this?   (disabling the 2nd gpu isnt a option, as it disables my main monitor output).

System details:
OS: Windows 10 Pro (64 bits)  21H2 (10.0.19044)
Processor: Intel® Core™ i7-9750H CPU @ 2.60GHz
Graphics:
- MS Idd Device
- MS Idd Device
- Intel® UHD Graphics 630
- NVIDIA GeForce GTX 1650
- MS Idd Device
Memory: 16 GB

**Comment by italocjs** [comment]
Not sure if it helps, but here is the log with the 2nd gpu disabled,  i tried everything i could find online to force the program to only use the intel GPU, but seems that its being ignored (or its 
another issue),   i had also tried installing an older driver for both gpus and no change.


[WinUsbDisplay.log](https://github.com/MindShow/USBDisplay/files/9191390/WinUsbDisplay.log)

**Comment by xbotuk** [comment]
I face same issue in Windows 11.

**Comment by Grea1722** [comment]
Have you had a breakthrough?

I have the same problem, apparently it is due to having two graphics cards.

**Comment by italocjs** [comment]
No idea how to fix, i tried:
- reinstalling all usbdisplay driver/software versions
- rolling back video drivers (for both gpus) to ~2 year ago (original driver for this laptop)
- tried replacing some dlls which also didnt help with the errors shown on the log.

I noticed this only happens when the second GPU is outputing a video signal, if the second GPU has nothing connected to its hdmi, the sofware works perfectly.  i'm guessing its something related to Win8ScreenDriverImpl (by googling it i found its from tightvnc, unfortunately a dead project).  

Some users of tightvnc had this error too, but i didnt found any fix there.

**Comment by Grea1722** [comment]
I found that the error is generated when you have 2 video cards, PC with a single video card drivers work perfectly.

**Comment by TentacleSama4254** [comment]
Same issue here, works with my laptop that has no dedicated GPUs

**Comment by LuigiPolidorio** [comment]
Same issue here, with the same GPU GeForce GTX 1650.

**Comment by MindShow** [comment]
try  this 2.7.0.10
http://www.ultrasemi.com/usbdisplay/Windows/USMDisplay_Windows.exe

**Comment by Grea1722** [comment]
Meh, still not working.

**Comment by miftkh** [comment]
> try this 2.7.0.10 http://www.ultrasemi.com/usbdisplay/Windows/USMDisplay_Windows.exe

not working.
previously, when i used the latest version, it worked, but the problems were there's no mouse cursor and low fps. but using this driver, it shows nothing.

**Comment by vsolovev** [comment]
Same thing there, 2.0.1.7.3 - showing up but no cursor and sooo laggy. Any other version - not showing at all. Laptop with UHD and Nvidia, configured usb display to use integrated card - nothing changes, still freezy. Waiting for fix

**Comment by MindShow** [comment]
this version support http://www.ultrasemi.com/usbdisplay/Windows/USMDisplay_Windows.exe

**Comment by vsolovev** [comment]
> this version support http://www.ultrasemi.com/usbdisplay/Windows/USMDisplay_Windows.exe

I've tried that and it doesn't work. Still no cursor and lags.

**Comment by italocjs** [comment]
Did anyone found a solution?

**Comment by italocjs** [comment]
> this version support http://www.ultrasemi.com/usbdisplay/Windows/USMDisplay_Windows.exe

No, it does not work! please reopen!

**Comment by josehenriqueujunior** [comment]
Having same troubles here.
