### ISSUE TITLE
Driver Windows 10 pro 21h1 64bits 

### ISSUE THREAD

**Issue by adonosod** [MindShow/USBDisplay#4]
application WinusbDisplay 1.0.1.6 opens and closes every 4 seconds.

buy 7 adapters for classes online please help!!!

Windows 10 pro 64b 21h1
Asus GL552jx
Nvidia gt950m / intel 4600 hd

**Comment by gabsfurtado** [comment]
Problem updating driver. I got the message "Uninstall has detected that XXX USB Display is current running" even after uninstalling.

**Comment by MindShow** [comment]
will you please post the systerm infomation exported by dxdiag and logs in the WinusbDisplay installed path

**Comment by MindShow** [comment]
> Problem updating driver. I got the message "Uninstall has detected that XXX USB Display is current running" even after uninstalling.

exit the program first
