### ISSUE TITLE
.dmg file does no mount

### ISSUE THREAD

**Issue by gabsfurtado** [MindShow/USBDisplay#5]
Every time i try to run it I got the message: The following disk images couldn't be opened - Reason: no file mountable systems

**Comment by MindShow** [comment]
maybe the file systerm was damaged，please try the driver apps in this repo

**Comment by gabsfurtado** [comment]
I have done it, but same results.
thanks for the answer.
![image](https://user-images.githubusercontent.com/86990616/127160254-e11a8de5-1027-468c-acc7-9261f5481ee8.png)

**Comment by MindShow** [comment]
use this file
https://github.com/MindShow/USBDisplay/blob/main/MacOS/MSDisplay_MacOS_v1.0.2b_20201125A.dmg
