### ISSUE TITLE
WIndows does not see the display

### ISSUE THREAD

**Issue by Arcadius2006** [MindShow/USBDisplay#50]
i am using a laptop with Windows 10 Home, and it refuses to recognize that there's a video output connected

the MS USB Display program _does_ recognize it, even saying if an output is connected or not

it might be also helpful to add that everything worked just fine yesterday.

**Comment by Arcadius2006** [comment]
also, have this:
[WinUsbDisplay.log](https://github.com/MindShow/USBDisplay/files/10409012/WinUsbDisplay.log)
it might help

**Comment by stephenz55** [comment]
I have tried a couple of hours to make the driver to work with my Win11 laptop, but failed every time. The main problems were:
1. The extend desktop mode does not work. I can see the third monitor which connected via an USB-HDMI dongle loaded with this "WinUSBDispaly" driver, but I could not extend the new monitor to my current desktop.
2. There are two usb devices with the lable: "Unknown USB Device (port reset failed)
If I right click the unknown usb device, and click on the "update driver", the yellow error mark will disappear. But device still not working.
Attached is my WinUsbDisplay.log.
Hope the issue will be fixed soon.  
[WinUsbDisplay.log](https://github.com/MindShow/USBDisplay/files/10561690/WinUsbDisplay.log)

**Comment by Arcadius2006** [comment]
i forgot to close this, the product i bought wasn't very good sooooo yeah
