### ISSUE TITLE
Mouse pointer does not appear on display in win11

### ISSUE THREAD

**Issue by cyasnyan** [MindShow/USBDisplay#53]
Dear MindShow.

MSDisplay_Windows_V2.0.1.7.3.exe

When I connect a USB display adapter with this build in win11, the mouse pointer does not appear.

https://www.amazon.co.jp/%E3%80%90OOOUSE-5Gbps%E9%AB%98%E9%80%9F%E4%BC%9D%E9%80%81%E3%80%91-%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%8C%E7%B0%A1%E5%8D%98-USB-HDMIi%E5%A4%89%E6%8F%9B%E3%82%A2%E3%83%80%E3%83%97%E3%82%BF%E3%83%BC-USB3-0-HDMI%E3%83%87%E3%82%A3%E3%82%B9%E3%83%97%E3%83%AC%E3%82%A4%E3%82%A2%E3%83%80%E3%83%97%E3%82%BF/dp/B0BG1QTCYK/ref=cm_cr_arp_d_product_top?ie=UTF8

**Comment by cyasnyan** [comment]
You had a issues. Close.

**Comment by Gumbraise** [comment]
Explain please ?
